server {
    listen 80;
    server_name helio-frontal;

    # Frontal HelioMed -> Juice Shop (simule l'appli patient / API Flask)
    location / {
        proxy_pass http://10.10.10.20:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Composant applicatif vulnérable de test -> DVWA
    location /dvwa/ {
        proxy_pass http://10.10.10.20:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
